### PR TITLE
update frontend gems

### PR DESCRIPTION
**Pull request by leonardow-unep-wcmc**

### CODE REVIEW

**Comment by leonardow-unep-wcmc** [comment]
Finished in 8 minutes 35 seconds (files took 6.28 seconds to load)
2146 examples, 0 failures, 21 pending

**Comment by pdl** [comment]
On `/admin/` I get the error `$(...).select2 is not a function` when running in development mode only, not production mode.

Screenshot from 2024-01-18 12-15-27

Compared to staging, the "Add new Taxon Concept" dropdown doesn't work but that's probably because subsequent js was not executed due to the error thrown above rather than the absence of select2.

**Comment by pdl** [comment]
The following gems have been removed and their contents moved to vendor/

- jquery-ui-rails
  - Added
    - `vendor/assets/javascripts/cites_trade/jquery-ui-1.10.4.custom.js`
  - Under `/trade`
    - `$.ui.version` returns `'1.9.2'`, same as staging
  - Under `/en/cites_trade`
    - `$.ui.version` returns `'1.10.4'`; staging returns `'1.10.3'` (acceptable change)
    - The green tabs on the left (e.g. "Exporting countries") work
- select2-rails
  - Added to
    - `/vendor/assets/javascripts/select2.js`
    - `/vendor/assets/stylesheets/select2.scss`
    - `/vendor/assets/images/select2{-spinner.gif,.png,x2.png}`
  - In `/en/cites_trade` the 'exporting countries' control is a select2
  - In `/admin/taxon_concepts/23/names`, The "Add new synonyms" button opens a modal; the "Select existing synonym:" field is a select2
- jquery-rails
  - Added to `vendor/assets/javascripts/jquery{,_ujs}.js`
  - Checked `Object.keys({...$}).sort()` as a proxy for version
    - `/` array length 106 vs 108 on staging - `cookie` and `removeCookie` were the missing keys due to change in jQuery Cookie to js cookie (expected change)
    - `/en/cites_trade` array length 116 vs 118 on staging for the same reason
    - `/admin` array length 105 vs 105
- jquery-mousewheel-rails
  - Added to `vendor/assets/javascripts/jquery.mousewheel.js`
  - Running `$('body').on('mousewheel', console.log);` then mousewheeling correctly spams the console with events on:
    - `/`
    - `/en/cites_trade`
    - `/admin`
- jquery-cookie-rails
  - Replaced with js cookie
    - STR:
      - Go to a search results page from the CITES Trade DB `/en/cites_trade/download?filters%5Btime_range_start%5D=2016&filters%5Btime_range_end%5D=2016&filters%5Bexporters_ids%5D%5B%5D=83&filters%5Bimporters_ids%5D%5B%5D=all_imp&filters%5Bsources_ids%5D%5B%5D=111&filters%5Bpurposes_ids%5D%5B%5D=all_pur&filters%5Bterms_ids%5D%5B%5D=all_ter&filters%5Btaxon_concepts_ids%5D%5B%5D=&filters%5Breset%5D=&filters%5Bselection_taxon%5D=taxonomic_cascade&web_disabled=`
      - Change the delimiter from comma to semicolon
      - Click 'Get report'
      - Copy the url and open it tin a new tab
      - New tab uses cookie to 'remember' your preference for semicolons
      - Enjoy your semicolons
    - Not used on `/admin` (`$.cookie` is undefined on staging)
- underscore-rails
  - Appears only used in two files directly:
      ```
      $ git grep -lP '^(?!//= require).*\b(underscore|_|lodash)\b' | grep -P '[.](js|coffee)' | grep -v vendor
      app/assets/javascripts/admin/taxon_concept_references.js.coffee
      app/assets/javascripts/cites_trade/application.js
      ```

    - In `cites_trade` this appear to be responsible for ensuring the dropdown of countries is populated
    - The `taxon_concept_references.js.coffee` is executed when you visit `/admin/taxon_concepts/12207/distributions` and click "Add new distribution location". Adding a logging line to that demonstrates that `_` is being correctly loaded.
  - Under `/`
    - `_.VERSION` returns `'1.4.4'`, same as staging
  - Under `/admin`
    - `_.VERSION` returns `'1.4.4'`, same as staging
  - Under `/en/cites_trade`
    - `_.VERSION` returns `'1.4.4'`, same as staging
- font-awesome-rails
  - Added to `/assets/fonts`
  - Under `/admin/`, cog appears in top right, pencil and bin appear in Actions column
  - Under `/#/elibrary`, info icon appears
  - Under `/trade`, buttons at bottom of page have cross, edit, download icons
  - Not used by `/en/cites_trade` - png icons are used instead



### Asset compilation in production mode

Note: When running in the `development` environment, assets don't go through the same pipeline as on production, which concatenates them into a single JS file and a single CSS file, reducing the number of requests on page load (saving >90% of page load time and even more important for high-latency environments). However, it's possible this pipeline could cause JS/CSS to behave differently, so I switched to testing on production mode.

In `config/environments/development.rb`, set:

```
config.assets.debug = false
config.assets.compile = false
```
And run

```
bundle exec rake assets:precompile
```

**Review by pdl — APPROVED** [review]

**Comment by pdl** [comment]
I've not been able to find anything broken by this change.

**Pull request merged**
