### PR TITLE
Add designation to documents

### PR DESCRIPTION
**Pull request by agnessa**
https://www.pivotaltracker.com/story/show/79507392

Adds designation to the document model, provides a way to update the value. There's also a rake task to populate default values where possible based on event type.

`rake db:migrate`
`rake elibrary:set_document_designation`
`REFRESH MATERIALIZED VIEW api_documents_mview`

### CODE REVIEW

**Comment by Levia** [comment]
When trying to edit a document assigning a different designation, it says "operation succeded" but the designation of that document doesn't change

**Comment by agnessa** [comment]
Perhaps it is a document linked to an event already, e.g. a CITES event and you try to change it to EU? in that case there's an automatic override so that data doesn't get messed up, let me know if the example you're testing is different.

**Comment by Levia** [comment]
Ah yes, with a different example it works by also refreshing the api_documents_mview. Is this correct?

**Comment by agnessa** [comment]
yes, it refreshes the mview offline after every document update

**Comment by Levia** [comment]
I had to refresh the table manually to see the changes in the designation column in the documents table, even if in the edit page everything looks updated.

**Comment by agnessa** [comment]
with sidekiq running?

**Comment by agnessa** [comment]
hang on, did you have to refresh the page or refresh the materialized view?

**Comment by Levia** [comment]
The materialised view. Yes sidekiq is running but when I restarted it everything has been updated. But apparently, when already running, I still need to updated the view manually or editing another document's designation to see the changes applied to the previously changed document

**Comment by agnessa** [comment]
I made changes to the document edit form, to prevent users from changing the designation when a documents is linked to an event is already linked to a designation (that was the confusing situation where previously it would look like you've updated the designation, but if it did not match with event then silently an override would ensure you have not created a conflict.)

**Comment by agnessa** [comment]
About that sidekiq thing though, I'm still not seeing the issue. What I see is after any update to the document it fires up an asynchronous worker, which refreshes the mview, so what you're seeing is curious. I guess one thing to check is if we're running sidekiq in the same way, i.e. I start it using bundle exec sidekiq -C config/sidekiq.yml; next thing to check is if perhaps you have a queue of old jobs to process, which would perhaps cause such behaviour - go to localhost:3000/sidekiq to see if you have anything "enqueued", maybe clear that before trying again?

**Comment by agnessa** [comment]
I also made a change to the sidekiq unique jobs gem configuration here (which for some reson upset travis a little). We previously had that gem to ensure only one RefreshDocumentsWorker is executing at a given time, to avoid locking up the database. But that did not prevent scheduling indefinite numbers of repetitions of the job, which I found problematic after I ran a large batch update recently to fix encoding on document titles. So I changed the uniqueness option to `until_and_while_executing`, which enforces uniqueness not only while executing, but also while scheduling (description of the different options here: https://github.com/mhenrixon/sidekiq-unique-jobs). But even after this change for individual updates I still see immediate execution of the refresh worker.

**Comment by Levia** [comment]
Cool! It works perfectly now apparently.

**Pull request merged**
