### PR TITLE
Rails4 fix invalid login

### PR DESCRIPTION
**Pull request by Levia**
## Description

Failing login attempts were throwing an error with regards the form.
Assign an empty user for the form to work and ensure the alert message shows in red.

## Notes

[Codebase ticket](https://unep-wcmc.codebasehq.com/projects/species-rails-4-upgrade/tickets/62)

### CODE REVIEW

**Comment by WKocur** [comment]
@Levia I'm happy - works for me. Did you want Luca to check before merging?

**Comment by lucacug** [comment]
@Levia  Is this also happening on the live site? or is the upgrade of the devise gem?

**Comment by Levia** [comment]
@lucacug I think that's the latter. Couldn't replicate in the current version of the site

**Comment by lucacug** [comment]
cool! Merging

**Pull request merged**
