### PR TITLE
Add clear button to elibrary search form

### PR DESCRIPTION
**Pull request by Levia**
This adds the clear button to the elibrary search form as in [this](https://www.pivotaltracker.com/story/show/109874868) PT story.
The clear button can be used anytime during the search

### CODE REVIEW

**Comment by agnessa** [comment]
We'll need Michel's input for the design, I think currently it is too easy to confuse search and clear. As far as functionality is concerned, sth goes wrong when clearing the event: set event type to CITES CoP, event to CoP 12, click search, then clear, then search again - selection is back at CoP 12 for me. Also sth not quite right with proposal outcome and review phase selection - they not get cleared, just hidden.

**Comment by Levia** [comment]
Thank you for spotting those issues. The deselection bugs should have been fixed with the last commit.

**Comment by agnessa** [comment]
OK, that works now. one thing I'm still seeing though is that when you select a CoP meeting, search, clear and search again, the meting is no longer selected by the meeting selector is visible - it should be hidden.

**Comment by Levia** [comment]
Ready to be reviewed again.

**Pull request merged**
