### PR TITLE
Remove S to A

### PR DESCRIPTION
**Pull request by agnessa**
https://www.pivotaltracker.com/story/show/115586203

Removed option from interface, cleaned model & specs. Also added missing primary output validations with specs.

### CODE REVIEW

**Comment by Levia** [comment]
I've noticed that the wizard lets you do T -> A without needing to specify a parent.
So for example, taking into account Panthera pardus delacouri from T to A, I can complete the status change successfully without specifying a parent into the corresponding wizard's step. Is this correct?

**Comment by agnessa** [comment]
you're right, it needs to validate the parent is present, probably with some cumbersome exceptions regarding plants and kingdoms, but it should be possible to reuse that logic from elsewhere

**Comment by agnessa** [comment]
I'll probably make a separate pull request for the parent fix, as it looks like a lot of changes in specs will need to follow.

**Comment by Levia** [comment]
Sounds good. Can I merge this then?

**Comment by agnessa** [comment]
yes - with the validation in place as in #568 this works as expected

**Comment by Levia** [comment]
There are tests failing while merging the current nomenclature_changes branch into this one. Could you please have a look as soon as you have the chance?

**Pull request merged**
