### PR TITLE
add server side download analytics model and tracking

### PR DESCRIPTION
**Pull request by WKocur**

### CODE REVIEW

**Comment by lucacug** [comment]
@WKocur  This is working well! I have also updated the file type (was pdf ?) to zip and used this branch for the text update needed for the new db version, hope that is ok?

**Comment by WKocur** [comment]
Fine by me :) Is this file size bit updated (I think it might be directly in the html....)
Screenshot 2021-07-01 at 15 00 42

**Comment by WKocur** [comment]
(@lucacug)

**Comment by lucacug** [comment]
Ah yeah, missed that bit. Done now Thanks!

**Pull request merged**
