### PR TITLE
added parent presence validation and fixed all the specs that got upset

### PR DESCRIPTION
**Pull request by agnessa**
Added a validation of parent presence, which is only effective for accepted names that happen not to be kingdoms. This one change in the TaxonConcept model has upset quite a number of specs.

Factory taxon_concept objects were previously created by default without parent and with a fixed rank. With the new validation in place the initialisation of those objects would fail either with "must have a parent" or "parent must be at immediately higher rank". The taxon concept factory now builds a parent for accepted names, and also makes sure the parent is of correct rank; that works recursively through the ancestors path.

To achieve correct rank assignment I also altered the rank factory, to ensure that we don't create duplicates of rank objects in a given test. That singleton behaviour was previously achieved by using a shared context with global [name_of_rank]_rank helpers - I removed that, as it wasn't helping in the factory context. The same behaviour is now achieved using alternative initialisation in the rank factory, in order to implement a "find or create" behaviour.

Also, many of the oldest specs relied on the former flexibility when constructing test objects, and so had to be amended to comply.

### CODE REVIEW

**Comment by Levia** [comment]
I have this as result when I click next at the very first step. Seems like the validation starts too early

screen shot 2016-03-16 at 17 36 02

**Comment by agnessa** [comment]
is that the T name that you changes previously to an A name? because in that case it is an A name without a parent, is that right?

**Comment by Levia** [comment]
Nope, what actually happens is that whatever T or S name I choose, I have the same error showing along with the status changed to A in the dropdown, for some reason.

**Comment by agnessa** [comment]
I see now, thanks!

**Comment by agnessa** [comment]
I believe this is now improved. The solution in case of the T -> A scenario was to remove the separate parent step and merge it with the primary_output step, as in fact setting a parent cannot be an isolated step as it is an integral attribute of a taxon concept.

The same issue was actually affecting other scenarios: lump output that is a synonym (after removing the option to use N/T as outputs), split output that is a synonym (after removing the option to use N/T as outputs) and swap. In all those cases I just added the parent taxon concept selector.

Some changes had to follow in the JS that handles the "output type" radio selector, which previously seemed to depend on the value of the parent field, which no longer worked (affects both splits and lumps).

**Pull request merged**
