### PR TITLE
Fix/query params

### PR DESCRIPTION
**Pull request by Levia**
## Description

Make sure URL is updated when searching for documents on the public interface, so that search results can be shared.

### CODE REVIEW

**Comment by lucacug** [comment]
It's working fine for me, except for this thing: when you search for Canis lupus for example and then click on one of the parent (Canide) the url change but nothing happens. Not sure how this is meant to work though @Levia @WKocur 
Screenshot from 2019-10-21 12-11-34

**Comment by WKocur** [comment]
@lucacug This could be related to the model not refreshing, which I've had to do manually. I might have missed one of the routes when doing this...

**Comment by WKocur** [comment]
@Levia Does this need to be sorted asap?

**Comment by lucacug** [comment]
@WKocur Yeah I think you got it right, this is the js error I got
```Error: Assertion Failed: Error: Assertion Failed: The URL '/taxon_concepts/4442/undefined?taxonomy=cites_eu&taxon_concept_query=Carnivora&geo_entities_ids=5&geo_entity_scope=cites&page=1' did not match any routes in your application```

**Comment by Levia** [comment]
Well spotted @lucacug !
I think it would be ideal if we could sort this out today so that the species team can test it.

Do you think you will have some time, @WKocur ?

**Comment by WKocur** [comment]
@Levia Sure - will take a look now :)

**Comment by lucacug** [comment]
This ends up being an issue on my local machine, I had to run `bundle install` :grimacing: 
Apologies @WKocur  :pray: 
Happy to merge now!!

**Pull request merged**
