### PR TITLE
Fix buggy accepted name or parent selectors

### PR DESCRIPTION
**Pull request by agnessa**
This addresses a number of issues from this rejected story: https://www.pivotaltracker.com/story/show/115605031

- the issue that would occur when trying to save a hybrid or N name with validation error - the window with the error was previously obscured by a new window rendered on top
- issue with parent / accepted name selectors that accepted fake names - currently all converted to the select2 selector (previously old typeahead) that forces a sensible selection
- following changes to the selectors, a simplification of logic in the TaxonConcept class
- some changes to the select2 selectors that allowed them to have the full functionality of old typeahead selectors, i.e. passing taxonomy, rank and rank scope to the autocomplete end-point. Passing the rank scope allows, for example, to constrain the parent autocomplete to just taxa of the rank above the new taxon rank
- added the rank selector for consistency to all nomenclature change outputs (previously we had it in swap and lump, now split and status to accepted also have it), which consequently allows to limit the parent taxon selectors depending on selected rank in the nomenclature change wizards as well
- restored front-end logic to limit number of hybrid parents and added back-end logic to validate the same
- fixed clearing the forms after closing
- removed code that became obsolete after those changes

### CODE REVIEW

**Comment by agnessa** [comment]
Forgot to add, what this is not handling is validating for presence of parents or accepted names for synonyms and hybrid parents for hybrids. This has never been in place so I suppose it should be handled as a different story if at all, because of the side effects on nomenclature change wizards. Adding the accepted names validation might require rework in all the wizards, where so far the step of saving linked names (e.g. accepted names for synonym) is separate from saving the synonym, which obviously would not work any more if we put such a validation in place.

**Comment by Levia** [comment]
Is the validation of parents for N names missing on purpose as well?

**Comment by agnessa** [comment]
I think you're right, probably there should be a parent presence validation for N names - will have another look at that.

**Comment by Levia** [comment]
Can I merge this? Everything seems to be fine now

**Comment by agnessa** [comment]
yes I think so, forgot to write here that I added the parent presence validation for N, but relaxed the 'parent name compatible' validation and did not enable the 'parent at immediately higher rank' validation, since I expect that could break things here and there once the dodgy E-Library N taxa are in.

**Pull request merged**
