### PR TITLE
New login design

### PR DESCRIPTION
**Pull request by Levia**
This PR is about the new login design.
It adds a link for loggin in at the bottom of the page, along with a modal window with the login form when clicking that button.
An ajax call has been implemented when logging in with the modal window so that we can display the errors correctly in the modal itself.

### CODE REVIEW

**Comment by agnessa** [comment]
can we push the footer further down the page - currently I see a gap below (screenshot from current production for comparison)

footer_with_gap_below_it
footer_without_gap_below_it

**Comment by agnessa** [comment]
I think I'd remove the "signed in successfully" flash alert - for me it's too bootstrappy for the public interface, and anyway the blue bar is prominent enough to give a visual cue that you're logged in - but that might be just my preference, what do you think @tomhazell @micheldoudin ?

logged_in_flash

**Comment by Levia** [comment]
About the gap below the footer, which browser (and maybe even the version) are you using? Because I can't see any gap in any of the browsers (including IE 8)

**Comment by agnessa** [comment]
I'm on FF, but it might be a resolution difference - on my smaller 14inch screen it does not happen, but I still see the difference between this version and production (i.e. footer starts lower down  in production)

**Comment by agnessa** [comment]
if possible I'd hide the login link once you've logged in

**Pull request merged**
