### PR TITLE
Id manual Identification event type

### PR DESCRIPTION
**Pull request by lucacug**
This add a new 'IdManual' event type to decouple these new documents from the intersessional ones (with event type `Other`).

:warning:  This may need further tests to make sure we don't break any other features, that's why the do not merge label

UPDATES

Rename the new event type to `IdMaterials`. We agreed to remove the do not merge label and do further tests after the deadline.
Now this includes the General/Part subfilter for either Manual and VC docs

### CODE REVIEW

**Comment by WKocur** [comment]
This is now linked up with the frontend and should work!

**Comment by WKocur** [comment]
@lucacug Do you have a plan for what will need testing here? Perhaps if we can get all the species+ relevant stuff merged and on staging, Species will have a chance to spot any problems. I haven't noticed anything apart from the document uploading admin interface. I've made a separate low priority ticket to deal with that, if you don't envisage it causing problems, provided no one is trying to upload id docs that way.

**Comment by lucacug** [comment]
@WKocur comments addressed. I renamed the FE bits to Material as well, maybe I went too far in process but it seems to work. Could you please double check and also feel free to amend.

**Comment by lucacug** [comment]
@WKocur I'm about to merge this and deploy to staging so I can run the importer of all the documents. Any objections?

**Pull request merged**
