### PR TITLE
update annual report upload transitions to add model

### PR DESCRIPTION
**Pull request by WKocur**
Seems previous ember was able to infer the model from the controller, so I've added the model into the transition params explicitly here. Also added config to respect nested routes.

https://unep-wcmc.codebasehq.com/projects/species-rails-4-upgrade/tickets/36

### CODE REVIEW

**Comment by Levia** [comment]
@WKocur This seems to work fine and I'm now able to get to the validation error page just fine! Also the save changes button works.

However, not sure if it was within the scope of this PR, but the `Cancel changes` button (the one next to Save Changes) is not working properly.
Also, even if grayed out when there are no changes, the `Save Changes` button seems to be clickable still. Clicking on that seems to trigger the changes regardless. It seems like the Cancel Changes button is only meant to disable the Save Changes one and remove the red tag mentioning the number of changes that have been made; it doesn't actually revert the changes from the record.

**Comment by WKocur** [comment]
@Levia Oops forgot to check the cancel - I'll fix that in this PR too. Thanks for spotting!

**Comment by WKocur** [comment]
I can't seem to fix this. It needs to rollback an ember transaction, but looks like the transaction is empty. Transactions were deprecated in ember2 and I can't find any docs so struggling to work out what's going on. As this seems to be an issue on normal staging, perhaps it can be separated into a low priority bug?

**Comment by Levia** [comment]
@WKocur Yeah I'm happy with that. As soon as it's logged into codebase we could come back to this later.
Happy for me to merge then?

**Comment by WKocur** [comment]
@Levia Yes, please do :) There was already a ticket for this, which I've tagged you in for your information. Have also moved to on hold after discussing with Jess.

**Pull request merged**
