### PR TITLE
Add trade codes to filters response endpoint

### PR DESCRIPTION
**Pull request by lucacug**
:warning:  This needs `bundle exec rake db:migrate` and may take ~40mins

To test the response: `http://localhost:9000/api/v1/trade_plus_filters` after a `redis-cli flushall`

Related trade plus [PR](https://github.com/unepwcmc/tradeplus/pull/56)

**UPDATE** July 2020

Add an extra sql view to make sure the formatting rules will be applied in the correct order:
so the "Standardise both term and unit" rules will be applied after all the other rules.

### CODE REVIEW

**Comment by WKocur** [comment]
@lucacug I have two terms with the same name and ID, but a different code:
78: {id: 84, code: "SKI", name: "Skins"}
79: {id: 84, code: "SKP", name: "Skins"}

**Comment by WKocur** [comment]
@lucacug This is working for me locally! Just checking with Aly on whether code or name should come first and thus whether we need to reorder the results. Will let you know as soon as I do :)

**Comment by WKocur** [comment]
@lucacug This is squeezing this in this PR a little, but the terms component returns the names as lowercase. Could they have the first letter capitalised, like the other components?

**Comment by WKocur** [comment]
@lucacug Ordering is fine in the backend - false alarm.

**Comment by lucacug** [comment]
@WKocur  The terms values are saved as lowercase in the db, I had to manually upcase them. Hoepfully looks good now.

**Comment by WKocur** [comment]
@lucacug All looking good from my perspective (I've popped this on staging). Is it worth Ferdi taking a look at the rules stuff before we merge?

**Comment by lucacug** [comment]
@WKocur That would be great thank you!

**Comment by WKocur** [comment]
@lucacug Could you update the description to describe the changes re ordering the formatting rules?

**Comment by Levia** [comment]
@lucacug @WKocur I haven't managed to go through this in details just yet, but there are a couple of things I could mention.
I gave this a go and migration ran fine. I wonder if you have noticed it being slower than usual? To me it seems that way but not sure if it's my laptop (as usually on staging is way faster). What worries me a bit on this regard is the extra SQL view added in between.

As I mentioned I haven't looked at the implementation details yet, but while I do this it would be great if you could please answer the above or if you think there's room for a slighlty different implementation that would avoid having this extra SQL view.

As far as the filters are concerned, if we can get confirmation that the data doesn't change often we could make those pre-cooked (even onto another db table) so that we will never experience the intial loading time. Not sure that could fit just now, but just had this thought.

**Comment by Levia** [comment]
Also wondered if 2 migrations are really necessary? It seems they are dropping and recreating almost the same views, so perhaps it could only be done once? I appreciate 2 might have been necessary during the implementation :)

**Comment by lucacug** [comment]
@Levia  Thanks Ferdi! If you mean the migrations are slower, that may be because there is an extra SQL view now. If you mean the app is slower, I didn't notice much difference with the previous version at a first glance.
The extra SQL view is the solution that came up into my mind to make sure the formatting rules will be applied in the correct order. I have tried to make it work refactoring the existing view but I wasn't able to do so. Happy to have a chat to try and find a better solution.
I'm not sure I got the point of the filters you mentioned and the extra db table.
Re double migrations I think you may be right, the first one is dated back to March, I totally miss that was in this same PR, so probably I could merge the 2 together.

**Comment by Levia** [comment]
@lucacug ok, thanks Luca!

I meant it's slower when running the application, but again, it might be my laptop and it would definitely be good to test it on staging.

About the filters, I meant that we should try to have those pre-loaded at deploy time rather then somebody having to trigger the first query that populates the cache. A way could be by running the SQL query to generate a db table with the pre-calculated filters any time there are changes, if data won't change too often.

If you could merge the 2 migrations into 1 it would be great :) thanks!

**Comment by WKocur** [comment]
@lucacug Is this ready for @Levia to look at again?

**Pull request merged**
