### PR TITLE
fixed incorrect display of tabs in IE8 caused by some quirk when inte…

### PR DESCRIPTION
**Pull request by agnessa**
rather unrefined fix for https://www.pivotaltracker.com/story/show/114193683

### CODE REVIEW

**Comment by Levia** [comment]
I still have the same issue on IE8 unfortunately.
screen shot 2016-02-24 at 16 01 29

**Comment by agnessa** [comment]
do you mean the table headers are centred instead of left-aligned? I didn't event notice that before, so they are :) but actually the thing I fixed was the 'Search results' header, that seems to have been improved. I'll see if there's a quick fix for the table headers.

**Comment by agnessa** [comment]
should be better now

**Comment by Levia** [comment]
Ah wow, I'm sorry! :sweat_smile: Those are both fine now then :)

**Pull request merged**
