### PR TITLE
Upgrade to Rails 4.2.11.3 and Ruby 2.5.9

### PR DESCRIPTION
**Pull request by leonardow-unep-wcmc**

### CODE REVIEW

**Comment by pdl** [comment]
There are a number of places where we're getting wrong numbers in tests, e.g. `rspec -e NomenclatureChange::ReassignmentCopyProcessor`.

For the failure:

```
  9) NomenclatureChange::ReassignmentCopyProcessor run when legislation is expected to eq 2
     Failure/Error: specify { expect(output_species1.listing_changes.count).to eq(2) }

       expected: 2
            got: 3

       (compared using ==)
     Shared Example Group: "legislation_reassignments_processor_examples" called from ./spec/models/nomenclature_change/reassignment_copy_processor_spec.rb:25
     # ./spec/models/nomenclature_change/shared/legislation_reassignments_processor_examples.rb:101:in `block (2 levels) in <top (required)>'
```

It looks like something is going wrong with the creation statements at the top of that file.

Adding in a `byebug` debugger line and printing off `output_species1.listing_changes`, we see:

```
# GOT (4.2)
[
  #<ListingChange id: 21611, taxon_concept_id: 303747, species_listing_id: 30167, change_type_id: 47452, annotation_id: 2090, hash_annotation_id: nil, effective_at: "2013-01-01 00:00:00", is_current: false, parent_id: nil, inclusion_taxon_concept_id: nil, event_id: nil, original_id: nil, explicit_change: true, created_at: "2024-01-10 14:09:04", updated_at: "2024-01-10 14:09:04", created_by_id: 44931, updated_by_id: 44931, nomenclature_note_en: nil, nomenclature_note_es: nil, nomenclature_note_fr: nil, internal_notes: nil>,
  #<ListingChange id: 21615, taxon_concept_id: 303747, species_listing_id: 30167, change_type_id: 47452, annotation_id: 2091, hash_annotation_id: nil, effective_at: "2013-01-01 00:00:00", is_current: false, parent_id: nil, inclusion_taxon_concept_id: nil, event_id: nil, original_id: nil, explicit_change: true, created_at: "2024-01-10 14:09:04", updated_at: "2024-01-10 14:09:04", created_by_id: 44931, updated_by_id: 44931, nomenclature_note_en: "", nomenclature_note_es: "", nomenclature_note_fr: "", internal_notes: "">, 
  #<ListingChange id: 21617, taxon_concept_id: 303747, species_listing_id: 30167, change_type_id: 47452, annotation_id: nil, hash_annotation_id: nil, effective_at: "2013-01-02 00:00:00", is_current: false, parent_id: nil, inclusion_taxon_concept_id: nil, event_id: nil, original_id: nil, explicit_change: true, created_at: "2024-01-10 14:09:04", updated_at: "2024-01-10 14:09:04", created_by_id: 44931, updated_by_id: 44931, nomenclature_note_en: "", nomenclature_note_es: "", nomenclature_note_fr: "", internal_notes: "">
]
```

```
# EXPECTED (4.1) 
[
  #<ListingChange id: 308, taxon_concept_id: 1270, species_listing_id: 163, change_type_id: 266, annotation_id: 52, hash_annotation_id: nil, effective_at: "2013-01-01 00:00:00", is_current: false, parent_id: nil, inclusion_taxon_concept_id: nil, event_id: nil, original_id: nil, explicit_change: true, created_at: "2024-01-11 10:57:56", updated_at: "2024-01-11 10:57:56", created_by_id: 136, updated_by_id: 136, nomenclature_note_en: "", nomenclature_note_es: "", nomenclature_note_fr: "", internal_notes: "">,
  #<ListingChange id: 313, taxon_concept_id: 1270, species_listing_id: 163, change_type_id: 266, annotation_id: nil, hash_annotation_id: nil, effective_at: "2013-01-02 00:00:00", is_current: false, parent_id: nil, inclusion_taxon_concept_id: nil, event_id: nil, original_id: nil, explicit_change: true, created_at: "2024-01-11 10:57:56", updated_at: "2024-01-11 10:57:56", created_by_id: 136, updated_by_id: 136, nomenclature_note_en: "", nomenclature_note_es: "", nomenclature_note_fr: "", internal_notes: "">
]
```

You can see that the 2013-01-01 appears twice in 4.2, once in 4.1. Additionally, in 4.2, there's something else going on with the text fields, which are null in one of the entries, and empty string in another.

**Comment by leonardow-unep-wcmc** [comment]
2146 examples, 0 failures, 21 pending

**Comment by pdl** [comment]
Spot-testing the frontend, things generally look in order.

Documents aren't downloading for me, but I suspect that might be a config issue?

To reproduce:

- Go to `/species#/documents?geo_entities_ids=203&event_type=CitesAc,CitesTc&events_ids=`
- Click on the `(+)` button and the first document
- This navigates to `/api/v1/documents/1698`
- Observed: rails 404 page

**Comment by leonardow-unep-wcmc** [comment]
> Spot-testing the frontend, things generally look in order.
> 
> Documents aren't downloading for me, but I suspect that might be a config issue?
> 
> To reproduce:
> 
>     * Go to `/species#/documents?geo_entities_ids=203&event_type=CitesAc,CitesTc&events_ids=`
> 
>     * Click on the `(+)` button and the first document
> 
>     * This navigates to `/api/v1/documents/1698`
> 
>     * Observed: rails 404 page

Look at `app/uploaders/document_file_uploader.rb:16`, the file is store in local file system.

**Pull request merged**
