### PR TITLE
Release 0.9.4

### PR DESCRIPTION
**Pull request by agnessa**
* fixes to T -> S and T -> A nomenclature changes processing
* geo entity auto complete matches on parts of name
* fixes to Trade Admin interface
* calculation of original start date for current EU suspensions
* ability to bulk update some shipment fields with blank value
* speed improvements to permit number auto complete
* fix for inherited standard reference flag
* linking EU Opinions to SRG events

tasks that need running:
* rake import:ec_srg
* rake map_eu_opinions_to_ec_srgs
* populate end dates for EU Suspensions
* rake map_eu_suspensions_to_terminating_regulations

### CODE REVIEW

**Comment by simaob** [comment]
&nbsp;<b>Code Climate</b> has <a href="https://codeclimate.com/repos/515da68789af7e6a9f00c08d/compare/release-0.9.4">analyzed this pull request</a>.

**Comment by simaob** [comment]
Code Climate called me saying that he liked the code very much. :+1:

**Comment by agnessa** [comment]
thank you for the sign-off :) not sure why CC is so keen to keep you involved :)

**Comment by simaob** [comment]
Maybe my account is somehow connected to Code Climate. Let me check.

**Comment by simaob** [comment]
I think the issue is that I set up the integration with Code Climate, instead of using the unepwcmc-read account*. I can revoke it, but might be better if you enable it with another account on the repo, so that the integration doesn't get lost in the ether.

* As part of my evil plan to be connected to SAPI FOREVER!!! I forgot to set this up for the ORS ;_; , but I still feel a small zap in my neck whenever a bug is found on the ORS or whenever someone curses at the looping sources.

**Comment by agnessa** [comment]
I can send you digests of my ORS rants :) OK I'll try to get this integration in place

**Comment by simaob** [comment]
Now I understand why my hears have been burning so much. :s I hope you are being able to make sense of it all! =) Let me know when you release some improved version so I can have a look and learn something new ;)

**Pull request merged**
